In [10]:
import pandas as pd

In [48]:
#df = pd.read_csv('vaccine_preprocessed_2.csv', sep='|')

In [49]:
#df.head(1)

In [135]:
df = pd.read_csv('vaccine_preprocessed_3.csv', sep='|')

In [136]:
df.head(1)

item_id category               title  \
0        1       AZ  澎湖確診數升 兒童疫苗接種率已逾7成   

                                             content  sentiment  \
0  澎湖COVID-19（2019冠狀病毒疾病）確診數攀升，澎湖縣政府今天公布新增182例，還有...        0.0   

                                             summary  \
0  ['澎湖5至11歲兒童疫苗接種種率已逾7成', '澎湖縣政府今天公布新增182例確診案例',...   

                                        top_key_freq  \
0  [('澎湖', 5), ('疫苗', 5), ('接種', 4), ('確診', 3), (...   

                                              tokens  \
0  ['澎湖', 'COVID-19', '（', '2019', '冠狀', '病毒', '疾...   

                                           tokens_v2  \
0  ['澎湖', '冠狀', '病毒', '疾病', '確診數', '澎湖縣', '政府', '...   

                                            entities  \
0  [NerToken(word='澎湖', ner='GPE', idx=(0, 2)), N...   

                                           token_pos  \
0  [('澎湖', 'Nc'), ('COVID-19', 'FW'), ('（', 'PARE...   

                                                link  
0  https://news.google.com/articles/CBMiMmh0dHBzO...

In [139]:
df['item_id'] = df['item_id'].apply(lambda x: str(x))

In [140]:
df.item_id	

0        1
1        2
2        3
3        4
4        5
      ... 
791    792
792    793
793    794
794    795
795    796
Name: item_id, Length: 796, dtype: object

In [123]:
item = []
for i in range(1, 797):
    print(i)
    item.append(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [124]:
item

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [103]:
datas = zip( item, df.category, df.title, df.sentiment, df.summary, df.top_key_freq, df.tokens, df.tokens_v2, df.link)
df_all = pd.DataFrame(list(datas), columns=['item_id', 'category','title','sentiment','summary','top_key_freq','tokens','tokens_v2','link'])
df_all

item_id category                               title  sentiment  \
0         1       AZ                  澎湖確診數升 兒童疫苗接種率已逾7成       0.00   
1         2       AZ        北市50多歲女打AZ疫苗後死亡 獲救濟金600萬史上最高       0.00   
2         3       AZ              日本評估打不完 取消4000萬劑AZ疫苗訂單       0.00   
3         4       AZ               AZ疫苗發明人警告 下一場大流行可能更致命       0.00   
4         5       AZ       AZ疫苗第2劑本週開放50至64歲預約 可望雙十連假前開打       0.00   
..      ...      ...                                 ...        ...   
791     792       高端               高端次世代新冠疫苗 今向食藥署申請人體試驗       0.99   
792     793       高端            高端疫苗難擋Delta？ 高端：對防重症仍有效果       0.00   
793     794       高端                新聞透視》從疫苗到快篩 國家隊不落外人田       0.00   
794     795       高端                轟疫苗政治凌駕專業 國民黨要求民進黨道歉       0.00   
795     796       高端  賴清德出訪接觸者陸續傳確診 柯P：打高端不見得沒效 但密醫上法庭必敗       0.00   

                                               summary  \
0    ['澎湖5至11歲兒童疫苗接種種率已逾7成', '澎湖縣政府今天公布新增182例確診案例',...   
1    ['金額介於6000元至600萬元、1案BNT疫苗救濟金額為2.5萬元', '台北市50多歲...   
2    ['預期今後日本國內施打AZ疫苗的人數不會大幅增加', '厚勞省至今共分配20萬劑AZ疫苗給...   
3    ['但「這不代表疫苗預防重症和死亡的能力也會下降', '但「這不會是病毒最後一次威脅人類的生...   
4    ['中央流行疫情指揮中心原規劃COVID-19（2019冠狀病毒疾病）疫苗第10輪10月3日...   
..                                                 ...   
791  ['美國將贈送150萬劑莫德納疫苗給台灣', '再次看到華航載著美國人的愛心-第二批150萬...   
792  ['12日打BNT疫苗有1萬2407人接種', '」桃園區公所不斷向在場民眾廣播「不用急在今...   
793  ['南韓累積莫德納疫苗到貨也已超過1500萬劑', '南韓政府總計向莫德納公司簽約購買400...   
794  ['高端疫苗（6547）辦理現金增資', '原本放棄原股東現增的基亞生技', '在董事會的支...   
795  ['第三劑打莫德納中和抗體上升倍數最高', '林口長庚醫院3月17日發表全國首份「新冠疫苗追...   

                                          top_key_freq  \
0    [('澎湖', 5), ('疫苗', 5), ('接種', 4), ('確診', 3), (...   
1    [('疫苗', 18), ('接種', 17), ('救濟', 16), ('個案', 12...   
2    [('疫苗', 12), ('日本', 9), ('接種', 5), ('施打', 4), ...   
3    [('疫苗', 5), ('病毒', 5), ('吉伯特', 4), ('變種', 3), ...   
4    [('疫苗', 12), ('預約', 8), ('接種', 7), ('意願', 6), ...   
..                                                 ...   
791  [('疫苗', 14), ('美國', 9), ('台灣', 9), ('政府', 5), ...   
792  [('疫苗', 11), ('桃園', 9), ('民眾', 8), ('接種', 5), ...   
793  [('疫苗', 15), ('莫德納', 13), ('南韓', 9), ('累積', 5)...   
794  [('疫苗', 4), ('股東', 4), ('完成', 3), ('全球', 3), (...   
795  [('陳時中', 8), ('接種', 6), ('確診', 5), ('疫苗', 5), ...   

                                                tokens  \
0    ['澎湖', 'COVID-19', '（', '2019', '冠狀', '病毒', '疾...   
1    ['衛福部', '預防', '接種', '受害', '救濟', '審議', '小組', '公...   
2    ['日本', '下', '訂', '1億2000萬', '劑', '英國', '阿斯特捷利康...   
3    ['AZ', '疫苗', '研發', '團隊', '領導人', '兼', '牛津', '大學...   
4    ['指揮', '中心', '今天', '公布', '，', 'AZ', '疫苗', '第2'...   
..                                                 ...   
791  ['美國', '在', '台', '協會', '（', 'AIT', '）', '今晚', ...   
792  ['公所', '人員', '、', '里長', '等', '人', '不斷', '向', '...   
793  ['南韓', '8月', '派出', '代表團', '向', '新冠', '肺炎', '疫苗...   
794  ['為', '因應', '國際', '出貨', '備料', '，', '高端', '疫苗',...   
795  ['陳時中', '確診', '！', '最', '新', '身體', '狀況', '曝\u3...   

                                             tokens_v2  \
0    ['澎湖', '冠狀', '病毒', '疾病', '確診數', '澎湖縣', '政府', '...   
1    ['衛福部', '接種', '救濟', '審議', '小組', '結果', '台北市', '...   
2    ['日本', '英國', '阿斯特捷利康', '疫苗', '日本', '接種', '疫苗',...   
3    ['疫苗', '研發', '團隊', '領導人', '牛津', '大學', '教授', '吉...   
4    ['指揮', '中心', '疫苗', '線上', '預約', '開放', '間隔', '民眾...   
..                                                 ...   
791  ['美國', '協會', '臉書', '發文', '美國', '莫德納', '疫苗', '台...   
792  ['公所', '人員', '里長', '在場', '民眾', '陳夢茹', '攝）', '桃...   
793  ['南韓', '派出', '代表團', '新冠', '肺炎', '疫苗廠', '莫德納', ...   
794  ['國際', '出貨', '備料', '疫苗', '辦理', '現金', '增資', '發行...   
795  ['陳時中', '確診', '身體', '狀況', '曝\u3000', '陳宗彥', '指...   

                                                  link  
0    https://news.google.com/articles/CBMiMmh0dHBzO...  
1    https://news.google.com/articles/CBMiMmh0dHBzO...  
2    https://news.google.com/articles/CBMiMmh0dHBzO...  
3    https://news.google.com/articles/CBMiN2h0dHBzO...  
4    https://news.google.com/articles/CBMiN2h0dHBzO...  
..                   

In [115]:
## 存成csv格式檔案
df_all.to_csv('vaccine_preprocessed_6.csv',sep="|", index=False)

In [113]:
df = pd.read_csv('vaccine_preprocessed_6.csv', sep='|')

In [116]:
df_all. item_id

0        1
1        2
2        3
3        4
4        5
      ... 
791    792
792    793
793    794
794    795
795    796
Name: item_id, Length: 796, dtype: object

In [22]:
item_id2idx={}
idx2item_id={}
for id, i in df.item_id.items():
    item_id2idx[i] = id
    idx2item_id[id] = i

In [23]:
item_id2idx

{'1': 0,
 '2': 1,
 '3': 2,
 '4': 3,
 '5': 4,
 '6': 5,
 '7': 6,
 '8': 7,
 '9': 8,
 '10': 9,
 '11': 10,
 '12': 11,
 '13': 12,
 '14': 13,
 '15': 14,
 '16': 15,
 '17': 16,
 '18': 17,
 '19': 18,
 '20': 19,
 '21': 20,
 '22': 21,
 '23': 22,
 '24': 23,
 '25': 24,
 '26': 25,
 '27': 26,
 '28': 27,
 '29': 28,
 '30': 29,
 '31': 30,
 '32': 31,
 '33': 32,
 '34': 33,
 '35': 34,
 '36': 35,
 '37': 36,
 '38': 37,
 '39': 38,
 '40': 39,
 '41': 40,
 '42': 41,
 '43': 42,
 '44': 43,
 '45': 44,
 '46': 45,
 '47': 46,
 '48': 47,
 '49': 48,
 '50': 49,
 '51': 50,
 '52': 51,
 '53': 52,
 '54': 53,
 '55': 54,
 '56': 55,
 '57': 56,
 '58': 57,
 '59': 58,
 '60': 59,
 '61': 60,
 '62': 61,
 '63': 62,
 '64': 63,
 '65': 64,
 '66': 65,
 '67': 66,
 '68': 67,
 '69': 68,
 '70': 69,
 '71': 70,
 '72': 71,
 '73': 72,
 '74': 73,
 '75': 74,
 '76': 75,
 '77': 76,
 '78': 77,
 '79': 78,
 '80': 79,
 '81': 80,
 '82': 81,
 '83': 82,
 '84': 83,
 '85': 84,
 '86': 85,
 '87': 86,
 '88': 87,
 '89': 88,
 '90': 89,
 '91': 90,
 '92': 91,
 '93': 

In [24]:
from transformers import AutoModel, AutoTokenizer
from transformers import BertTokenizer, BertModel
import torch
import numpy as np

In [25]:
#model = AutoModel.from_pretrained('ckiplab/albert-tiny-chinese') # 中研院更輕量BERT
model = AutoModel.from_pretrained('ckiplab/albert-base-chinese') # 中研院輕量BERT
#model = AutoModel.from_pretrained('bert-base-chinese') # Google
#model = BertModel.from_pretrained('bert-base-chinese', output_hidden_states=True)

Some weights of the model checkpoint at ckiplab/albert-base-chinese were not used when initializing AlbertModel: ['predictions.decoder.bias', 'predictions.bias', 'predictions.dense.bias', 'predictions.dense.weight', 'predictions.LayerNorm.bias', 'predictions.decoder.weight', 'predictions.LayerNorm.weight']
- This IS expected if you are initializing AlbertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing AlbertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of AlbertModel were not initialized from the model checkpoint at ckiplab/albert-base-chinese and are newly initialized: ['albert.pooler.weight', 'albert.pooler.bias']
You should probably TRAIN this model on a down-stream t

In [26]:
print(model)

AlbertModel(
  (embeddings): AlbertEmbeddings(
    (word_embeddings): Embedding(21128, 128, padding_idx=0)
    (position_embeddings): Embedding(512, 128)
    (token_type_embeddings): Embedding(2, 128)
    (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0, inplace=False)
  )
  (encoder): AlbertTransformer(
    (embedding_hidden_mapping_in): Linear(in_features=128, out_features=768, bias=True)
    (albert_layer_groups): ModuleList(
      (0): AlbertLayerGroup(
        (albert_layers): ModuleList(
          (0): AlbertLayer(
            (full_layer_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (attention): AlbertAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (attention_dropout): Dropout(p=0, inplace=False)
      

In [27]:
tokenizer = AutoTokenizer.from_pretrained('ckiplab/albert-base-chinese')
#tokenizer = AutoTokenizer.from_pretrained('bert-base-chinese') # Google
# tokenizer = BertTokenizer.from_pretrained("bert-base-chinese")

In [28]:
tokenizer

PreTrainedTokenizerFast(name_or_path='ckiplab/albert-base-chinese', vocab_size=21128, model_max_len=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})

In [29]:
# (1) A string
sentences = '水果很多對人有好處，比如蘋果'
sentences_tokens = tokenizer(sentences, return_tensors='pt')
sentences_tokens

{'input_ids': tensor([[ 101, 3717, 3362, 2523, 1914, 2205,  782, 3300, 1962, 5993, 8024, 3683,
         1963, 5981, 3362,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [30]:
# (2) A list of a string (A list contains only a string element)
sentences = ['水果很多對人有好處，比如蘋果']
sentences_tokens = tokenizer(sentences, return_tensors='pt')
sentences_tokens

{'input_ids': tensor([[ 101, 3717, 3362, 2523, 1914, 2205,  782, 3300, 1962, 5993, 8024, 3683,
         1963, 5981, 3362,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [31]:
# (3) A list of batch strings (A list contains several string elements)
sentences = ['水果很多對人有好處，比如蘋果','外國手機有很多都不错，比如蘋果','我喜歡吃不同水果，比如蘋果']
sentences_tokens = tokenizer(sentences, return_tensors='pt', padding=True, truncation=True)
#sentences_tokens = tokenizer(sentences, return_tensors='pt') # error
#sentences_tokens = tokenizer(sentences, return_tensors='pt', max_length=20, padding='max_length')
sentences_tokens

{'input_ids': tensor([[ 101, 3717, 3362, 2523, 1914, 2205,  782, 3300, 1962, 5993, 8024, 3683,
         1963, 5981, 3362,  102,    0],
        [ 101, 1912, 1751, 2797, 3582, 3300, 2523, 1914, 6963,  679, 7231, 8024,
         3683, 1963, 5981, 3362,  102],
        [ 101, 2769, 1599, 3631, 1391,  679, 1398, 3717, 3362, 8024, 3683, 1963,
         5981, 3362,  102,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])}

In [32]:
# 送入模型取得輸出
# (2) A list of a string (A list contains only a string element)
sentences = ['水果很多對人有好處，比如蘋果']
#sentences = ['水果很多對人有好處，比如蘋果','外國手機有很多都不错，比如蘋果','我喜歡吃不同水果，比如蘋果']
sentences_tokens = tokenizer(sentences, return_tensors='pt', padding=True, truncation=True)
outputs = model(sentences_tokens.input_ids)

In [33]:
outputs

BaseModelOutputWithPooling(last_hidden_state=tensor([[[ 0.1013, -0.0104, -0.0303,  ...,  0.0479,  0.0259,  0.0390],
         [ 0.7448, -0.3410, -0.2156,  ...,  0.2374, -0.5448, -0.2546],
         [ 1.1505, -0.7310, -0.4481,  ...,  0.2867, -0.5794, -0.0653],
         ...,
         [ 0.1480,  0.0464, -0.1910,  ...,  0.0167, -0.5270, -0.1716],
         [ 0.6995, -0.3785,  0.0233,  ...,  0.0541, -0.7188,  0.2812],
         [ 0.0955, -0.0167, -0.0300,  ...,  0.0477,  0.0246,  0.0428]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[ 9.8699e-02,  1.0969e-02, -1.1147e-01,  6.8402e-02,  8.4471e-03,
          6.5685e-02,  2.1609e-02,  1.5147e-01,  1.4478e-01, -1.2170e-01,
          1.0032e-01, -3.1631e-02,  4.2556e-02, -5.3948e-02,  2.1133e-01,
         -1.1126e-01, -7.5157e-02, -2.5161e-01,  1.2144e-02, -3.6276e-02,
          1.6301e-01,  2.4643e-02,  6.8334e-02,  1.3013e-02,  1.3401e-01,
          7.2149e-02,  1.1617e-01, -1.3357e-01, -2.4199e-01, -3.2134e-02,
         -3

In [34]:
list(outputs)

['last_hidden_state', 'pooler_output']

In [35]:
outputs['last_hidden_state'].shape

torch.Size([1, 16, 768])

In [36]:
outputs['pooler_output'].shape

torch.Size([1, 768])

In [37]:
# 中間的維度是字數，此例是17
outputs['last_hidden_state'].shape

torch.Size([1, 16, 768])

In [38]:
last_hidden_state = outputs['last_hidden_state']

In [39]:
vectors = torch.mean(last_hidden_state, dim=1) # global_average_pooling shape (1, 768)

In [40]:
vectors.size()

torch.Size([1, 768])

In [41]:
vectors

tensor([[ 1.6976e-01, -1.6507e-01, -1.1538e-01,  6.0885e-02, -3.3758e-01,
          7.6232e-02, -4.1813e-02, -9.1156e-04,  5.3974e-02, -4.9231e-02,
         -3.1877e-02, -2.4234e-01,  3.2062e-01, -4.5942e-02, -1.2311e-01,
         -5.8557e-02, -1.1227e-01, -3.9124e-02,  4.6919e-01, -2.1179e-01,
         -7.7214e-02, -2.0720e-01, -5.5635e-02,  4.0997e-01,  1.3981e-01,
          1.1735e-01,  1.0266e-01,  2.2062e-01,  2.0268e-04,  2.7118e-02,
         -3.3598e-01, -7.8526e-01, -1.2152e-01,  1.8300e-01,  2.4748e-01,
         -2.2188e-01, -1.7569e-02,  2.8890e-02,  4.2054e-02, -2.7343e-03,
         -2.2754e-01, -6.0097e-02,  1.5023e-01,  8.0421e-03,  3.6072e-01,
         -3.3834e-01, -1.7850e-01, -1.3352e-01, -4.3545e-02,  1.3781e-01,
         -2.5791e-01,  8.7933e-02,  1.4905e-01,  8.6724e-02, -1.1089e-02,
         -2.0348e-02,  1.3039e-01, -1.8207e-01, -2.0819e-01, -2.5779e-01,
         -7.7849e-02, -1.0238e-01, -2.7244e-02, -1.4555e-01, -4.3418e-01,
         -6.0629e-02,  1.7174e-01, -4.

In [42]:
vectors.detach().numpy()

array([[ 1.69760108e-01, -1.65073663e-01, -1.15377285e-01,
         6.08854592e-02, -3.37576032e-01,  7.62322322e-02,
        -4.18130755e-02, -9.11558978e-04,  5.39744683e-02,
        -4.92311195e-02, -3.18767689e-02, -2.42336839e-01,
         3.20616424e-01, -4.59418558e-02, -1.23114362e-01,
        -5.85574433e-02, -1.12266399e-01, -3.91243286e-02,
         4.69185233e-01, -2.11785346e-01, -7.72140175e-02,
        -2.07203001e-01, -5.56351878e-02,  4.09969538e-01,
         1.39805585e-01,  1.17348567e-01,  1.02656938e-01,
         2.20622793e-01,  2.02679308e-04,  2.71175057e-02,
        -3.35977197e-01, -7.85260916e-01, -1.21520750e-01,
         1.83004647e-01,  2.47477874e-01, -2.21884131e-01,
        -1.75685436e-02,  2.88897511e-02,  4.20543142e-02,
        -2.73427786e-03, -2.27535635e-01, -6.00965358e-02,
         1.50226876e-01,  8.04206450e-03,  3.60715330e-01,
        -3.38335395e-01, -1.78499654e-01, -1.33520335e-01,
        -4.35447283e-02,  1.37811691e-01, -2.57908255e-0

In [43]:
with torch.no_grad():
    vectors.numpy()

In [44]:
# 送入模型取得輸出
# (2) A list of a string (A list contains only a string element)
sentences = df.content[0:5].to_list()
sentences_tokens = tokenizer(sentences, return_tensors='pt', padding=True, truncation=True)
outputs = model(sentences_tokens.input_ids)

In [45]:
outputs

BaseModelOutputWithPooling(last_hidden_state=tensor([[[ 4.5294e-02,  6.8923e-03, -2.4707e-01,  ...,  1.0339e-01,
           6.5166e-01, -2.8055e-01],
         [ 1.3294e-01,  5.8795e-02,  6.2787e-01,  ..., -3.1194e-01,
           1.0823e-01,  1.8447e-01],
         [-7.3630e-01,  6.3455e-02,  2.0290e-01,  ...,  1.2692e-01,
          -8.1296e-02,  1.9754e-01],
         ...,
         [-2.6222e-01, -2.5971e-01, -2.3064e-01,  ...,  8.5218e-02,
           9.9629e-02, -9.3927e-02],
         [-3.3368e-01, -1.8825e-01,  3.7928e-02,  ...,  2.1045e-02,
           1.1597e-01, -1.6468e-01],
         [-2.0186e-01, -4.8247e-01, -5.7307e-01,  ...,  4.3777e-02,
           2.2264e-01, -1.3875e-01]],

        [[ 1.5799e-01,  1.1054e-02, -3.5785e-02,  ...,  3.8219e-01,
           3.5287e-01, -1.5441e-01],
         [-1.8254e-01, -3.4625e-01, -2.9633e-01,  ...,  4.7803e-01,
          -9.0851e-01,  7.1785e-01],
         [-6.6004e-01,  4.2973e-02, -5.0407e-01,  ..., -1.3513e-01,
          -1.6388e-01,  7.6594e

In [46]:
list(outputs)

['last_hidden_state', 'pooler_output']

In [47]:
outputs['last_hidden_state'].shape

torch.Size([5, 512, 768])

In [48]:
last_hidden_state = outputs['last_hidden_state']

In [49]:
vectors = torch.mean(last_hidden_state, dim=1) # global_average_pooling shape (1, 768)

In [32]:
vectors.size()

torch.Size([5, 768])

In [33]:
sentences = ['水果很多對人有好處，比如蘋果','外國手機有很多都不错，比如蘋果','我喜歡吃不同水果，比如蘋果']

In [34]:
sentences_tokens = tokenizer(sentences, return_tensors='pt', padding=True, truncation=True)
vectors = torch.mean(model(sentences_tokens.input_ids)['last_hidden_state'], dim=1) # global_average_pooling shape (1, 768)

In [35]:
vectors

tensor([[ 0.0082, -0.1978, -0.1236,  ...,  0.1618, -0.2955,  0.0351],
        [ 0.0924,  0.0160,  0.0262,  ...,  0.1537, -0.3317,  0.0321],
        [-0.0609, -0.2085, -0.1737,  ...,  0.1453, -0.4900, -0.0351]],
       grad_fn=<MeanBackward1>)

In [36]:
vectors.shape

torch.Size([3, 768])

In [37]:
def get_vector(sentence):
    tokens = tokenizer(sentence, return_tensors='pt', truncation=True, padding=True)
    vector = torch.mean(model(tokens.input_ids)['last_hidden_state'], dim=1).detach().numpy() # global_average_pooling shape (1, 768)
    #vector = torch.mean(model(tokens.input_ids)['last_hidden_state'], dim=1) # global_average_pooling shape (1, 768)
    return vector[0] # (1, 768)第一個維度是批量1 回傳其向量一維度即可

In [38]:
df.shape

(796, 12)

In [39]:
len(df.content.to_list())

796

In [40]:
%%time
# It takes more than 2 minitues. 213 samples
sentences =  df.content.to_list()
news_vectors = [get_vector(sentence) for sentence in sentences]

CPU times: total: 46min 54s
Wall time: 7min 54s


In [41]:
news_vectors = np.array(news_vectors)

In [42]:
news_vectors.shape

(796, 768)

In [43]:
len(news_vectors)

796

In [44]:
news_vectors[0].shape

(768,)

In [45]:
news_vectors[0]

array([ 2.69885659e-01, -1.90711811e-01,  1.50639964e-02,  1.66448012e-01,
       -6.07861400e-01,  1.26061484e-01,  1.51300253e-02,  3.03549767e-02,
        2.72015721e-01, -1.73093870e-01, -3.22774686e-02,  1.16457470e-01,
       -4.19570543e-02, -6.78414702e-02,  6.40978292e-02, -2.10778210e-02,
       -1.68506920e-01,  1.02310039e-01,  3.96144902e-03, -6.99906573e-02,
        9.53166261e-02, -4.01505381e-01, -2.32386608e-02,  4.44948167e-01,
        1.22952238e-01, -3.53017007e-03,  4.65322703e-01,  2.21050769e-01,
        1.66999161e-01, -1.66270986e-01, -2.39368737e-01,  6.46797776e-01,
       -8.58127549e-02, -1.03501067e-01,  1.78674549e-01, -6.37075976e-02,
        8.05151388e-02, -4.21226844e-02,  1.61646064e-02, -1.82247952e-01,
        9.72851515e-02, -1.90292343e-01, -2.28693917e-01, -8.89147967e-02,
       -4.01813745e-01, -1.63746670e-01, -3.22723359e-01,  2.97907572e-02,
        5.02038747e-02, -1.09260373e-01,  8.20283666e-02,  6.52114600e-02,
        6.95330277e-02,  

In [46]:
np.save('news_vectors_3.npy',news_vectors)

In [47]:
news_vectors = np.load('news_vectors_3.npy')

In [48]:
news_vectors.shape

(796, 768)

In [49]:
news_vectors[0]

array([ 2.69885659e-01, -1.90711811e-01,  1.50639964e-02,  1.66448012e-01,
       -6.07861400e-01,  1.26061484e-01,  1.51300253e-02,  3.03549767e-02,
        2.72015721e-01, -1.73093870e-01, -3.22774686e-02,  1.16457470e-01,
       -4.19570543e-02, -6.78414702e-02,  6.40978292e-02, -2.10778210e-02,
       -1.68506920e-01,  1.02310039e-01,  3.96144902e-03, -6.99906573e-02,
        9.53166261e-02, -4.01505381e-01, -2.32386608e-02,  4.44948167e-01,
        1.22952238e-01, -3.53017007e-03,  4.65322703e-01,  2.21050769e-01,
        1.66999161e-01, -1.66270986e-01, -2.39368737e-01,  6.46797776e-01,
       -8.58127549e-02, -1.03501067e-01,  1.78674549e-01, -6.37075976e-02,
        8.05151388e-02, -4.21226844e-02,  1.61646064e-02, -1.82247952e-01,
        9.72851515e-02, -1.90292343e-01, -2.28693917e-01, -8.89147967e-02,
       -4.01813745e-01, -1.63746670e-01, -3.22723359e-01,  2.97907572e-02,
        5.02038747e-02, -1.09260373e-01,  8.20283666e-02,  6.52114600e-02,
        6.95330277e-02,  

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

In [53]:
news_sim_martrix = cosine_similarity(news_vectors, news_vectors)

In [54]:
news_sim_martrix.shape

(796, 796)

In [55]:
news_sim_martrix

array([[1.        , 0.8577324 , 0.9283546 , ..., 0.853668  , 0.7824096 ,
        0.8587448 ],
       [0.8577324 , 1.        , 0.79619414, ..., 0.95012784, 0.6327616 ,
        0.97186434],
       [0.9283546 , 0.79619414, 1.0000004 , ..., 0.81210184, 0.8544677 ,
        0.795104  ],
       ...,
       [0.853668  , 0.95012784, 0.81210184, ..., 1.0000001 , 0.6359547 ,
        0.9679518 ],
       [0.7824096 , 0.6327616 , 0.8544677 , ..., 0.6359547 , 1.0000002 ,
        0.6407591 ],
       [0.8587448 , 0.97186434, 0.795104  , ..., 0.9679518 , 0.6407591 ,
        0.9999999 ]], dtype=float32)

In [56]:
import numpy as np

np.save('news_sim_martrix_3.npy', news_sim_martrix)

news_sim_martrix = np.load('news_sim_martrix_3.npy')

In [57]:
item_id = 1

In [58]:
idx = item_id2idx[item_id]

In [59]:
idx

0

In [60]:
df.content[0]

'澎湖COVID-19（2019冠狀病毒疾病）確診數攀升，澎湖縣政府今天公布新增182例，還有一名接種2劑疫苗的92歲確診女性不治。另外，澎湖5至11歲兒童疫苗接種種率已逾7成。澎湖縣政府表示，92歲女性長者己施打過2劑AZ疫苗，6日經診所通報確診，申請居家照護，7日因呼吸急性衰竭，送衛福部澎湖醫院急診，今天凌晨不幸過世，確切死因仍需由中央疫情指揮中心認定。澎湖縣政府表示，澎湖5至11歲兒童疫苗接種，全縣37所國小和9所幼兒園4569名學童中，目前完成莫德納與輝瑞兒童疫苗接種者，分別有1108和2278人，接種率逾7成。澎湖縣政府今天公布新增182例確診案例，外籍人士4例、外縣市1例，其餘177例均為澎湖籍，以20至29歲和30至39歲年齡層，各為31人最多，年紀最小是10個月大男童，最長為101歲女性，除集中檢疫所和三總各收治1例外，其餘全數申請居家照護照。澎湖累積有3896例確診，目前還收治有1030人。'

In [61]:
news_sim_martrix[0]

array([1.        , 0.8577324 , 0.9283546 , 0.8350728 , 0.84491515,
       0.8499739 , 0.94553626, 0.85721976, 0.9445167 , 0.85875404,
       0.8205571 , 0.8506931 , 0.85805446, 0.86968434, 0.91871077,
       0.94901085, 0.77775216, 0.8373644 , 0.86546326, 0.93423736,
       0.9120275 , 0.8608369 , 0.9432019 , 0.85305125, 0.86031425,
       0.86171013, 0.8966484 , 0.84753585, 0.8506766 , 0.85517985,
       0.94886804, 0.8523972 , 0.86483264, 0.8455106 , 0.9311109 ,
       0.855201  , 0.93595475, 0.8528276 , 0.8576288 , 0.9130043 ,
       0.8432647 , 0.85530895, 0.861858  , 0.8642226 , 0.9450809 ,
       0.9465506 , 0.8471748 , 0.8495383 , 0.846722  , 0.8619251 ,
       0.84406334, 0.8573401 , 0.9425538 , 0.93619585, 0.84922254,
       0.8615557 , 0.92963684, 0.8537413 , 0.86062545, 0.8546165 ,
       0.8491643 , 0.85204434, 0.8645701 , 0.8528832 , 0.8557117 ,
       0.85545814, 0.9447484 , 0.9227653 , 0.96488595, 0.8525221 ,
       0.85645115, 0.86966395, 0.8389679 , 0.85867536, 0.93567

In [62]:
news_sim_martrix[0][:20]

array([1.        , 0.8577324 , 0.9283546 , 0.8350728 , 0.84491515,
       0.8499739 , 0.94553626, 0.85721976, 0.9445167 , 0.85875404,
       0.8205571 , 0.8506931 , 0.85805446, 0.86968434, 0.91871077,
       0.94901085, 0.77775216, 0.8373644 , 0.86546326, 0.93423736],
      dtype=float32)

In [63]:
sim_dict = {}
idx = item_id2idx[item_id]  # 0 for 'aipl_20220314_1'
for i, value in enumerate(news_sim_martrix[idx]):
    sim_dict[i]=value

In [64]:
sim_dict

{0: 1.0,
 1: 0.8577324,
 2: 0.9283546,
 3: 0.8350728,
 4: 0.84491515,
 5: 0.8499739,
 6: 0.94553626,
 7: 0.85721976,
 8: 0.9445167,
 9: 0.85875404,
 10: 0.8205571,
 11: 0.8506931,
 12: 0.85805446,
 13: 0.86968434,
 14: 0.91871077,
 15: 0.94901085,
 16: 0.77775216,
 17: 0.8373644,
 18: 0.86546326,
 19: 0.93423736,
 20: 0.9120275,
 21: 0.8608369,
 22: 0.9432019,
 23: 0.85305125,
 24: 0.86031425,
 25: 0.86171013,
 26: 0.8966484,
 27: 0.84753585,
 28: 0.8506766,
 29: 0.85517985,
 30: 0.94886804,
 31: 0.8523972,
 32: 0.86483264,
 33: 0.8455106,
 34: 0.9311109,
 35: 0.855201,
 36: 0.93595475,
 37: 0.8528276,
 38: 0.8576288,
 39: 0.9130043,
 40: 0.8432647,
 41: 0.85530895,
 42: 0.861858,
 43: 0.8642226,
 44: 0.9450809,
 45: 0.9465506,
 46: 0.8471748,
 47: 0.8495383,
 48: 0.846722,
 49: 0.8619251,
 50: 0.84406334,
 51: 0.8573401,
 52: 0.9425538,
 53: 0.93619585,
 54: 0.84922254,
 55: 0.8615557,
 56: 0.92963684,
 57: 0.8537413,
 58: 0.86062545,
 59: 0.8546165,
 60: 0.8491643,
 61: 0.85204434,
 

In [65]:
df.content[11]

'研究顯示，AZ混打莫德納疫苗對Delta保護力優於2劑AZ疫苗。指揮中心今天表示，完整接種AZ疫苗可有效預防重症、死亡，副作用也比混打少，呼籲打AZ的民眾無須悲觀以對。台大醫院今天公布COVID-19（2019冠狀病毒疾病）疫苗混打試驗成果，AZ混打莫德納疫苗不僅抗體濃度比打2劑AZ疫苗者高，體外試驗也發現，接種14天後對抗最早在印度發現的Delta變異株的保護力達到100%，是2劑AZ疫苗的5倍。台灣大學副校長、中央流行疫情指揮中心專家諮詢小組召集人張上淳今天接受記者電話聯訪時解釋，該研究用受試者稀釋40倍的血液，測試能否中和病毒，若能順利中和病毒則視為具有保護力，並不代表在真實世界中也擁有100%保護力。研究結果出爐後，有不少接種2劑AZ疫苗的民眾擔心保護力不足。中央流行疫情指揮中心醫療應變組副組長羅一鈞今天下午在疫情記者會中表示，評估疫苗的效果除了要考慮保護力，也要一併考量抗體效價、副作用等問題，以及真實世界中的確診情形，畢竟疫苗接種一段時間後，保護力會逐漸下降，也可能出現突破性感染等狀況。羅一鈞並指出，該研究2劑AZ疫苗接種僅相隔8週，真實世界中可能長達12週，且根據國外數據顯示，2劑AZ疫苗間隔愈長，抗體生成、保護力都比較好，呼籲民眾不用悲觀地認為打2劑AZ疫苗效果較差，實際上對於預防重症、死亡的保護效果都不錯，副作用也比混打來得輕微。指揮中心指揮官陳時中表示，無論打2劑同廠牌疫苗，或是混打2種不同廠牌疫苗，都有其利和弊，民眾可自己做最好選擇。另外，有專家質疑指揮中心開放接種高端疫苗者，有出國需求，可混打其他國際認證疫苗，形同否定高端疫苗。陳時中反問：「要不然要怎麼辦」，政府總不可能讓民眾打完高端疫苗，結果飛到美國無法入境，又被趕回來，因此才會開放有出國需求者接種其他疫苗，目的是解決入境的問題，但強調混打不同廠牌疫苗就是有其風險。'

In [66]:
from operator import itemgetter
sorted_sim_dict = sorted(sim_dict.items(), key= itemgetter(1), reverse=True)

In [67]:
topk_sim_dict = sorted_sim_dict[1:3] # skip 0 自己跟自己的相似度

In [68]:
for idx, value in topk_sim_dict:
    print(value, df.content.iloc[idx])

0.96921134 為鼓勵長者施打疫苗，花蓮縣政府今天指出，縣內65歲以上、原住民族55歲以上長者即日起施打疫苗，加贈2劑快篩試劑，施打第1、2劑者加碼價值新台幣500元衛教品。花蓮縣政府下午召開COVID-19（2019冠狀病毒疾病）記者會，衛生局長朱家祥指出，為鼓勵長者打疫苗，即日起至6月30日，65歲以上長者及55歲原民長者接種疫苗可獲2劑快篩試劑；5月31日前長者施打第1、2劑縣府加碼500元衛教品。朱家祥表示，縣內提供「0+7」自主防疫者、「3+4」居家隔離及自主防疫者，每人2劑、3劑快篩試劑，同住家人可憑健保卡及身分證領取快篩試劑。朱家祥指出，花蓮新增確診人數1291例，其中18歲以下占2成，與上週實體課程期間確診比例差不多，顯示實體課程與遠距教學對與染疫比率並無顯著影響。不過記者會後，縣府改發布快訊，宣布花蓮縣高中以下（公私立含幼兒園）暫停實體課程，延長遠距教學至6月2日。花蓮縣政府教育處代理處長翁書敏表示，縣府調查5歲至17歲校院接種BNT疫苗意願，共計發出3萬1859份問卷，目前回收2萬4087份，同意接種比例為61.24%，呼籲尚未繳回意願表的家長，盡快評估回報，以利學校施打作業。
0.9670428 苗栗縣今天新增確診COVID-19（2019冠狀病毒疾病）1509例，針對65歲以上長者施打第4劑疫苗，18日將在7鄉鎮開設大型接種站，其餘11鄉鎮由轄區衛生所規劃施打日程。苗栗縣衛生局透過新聞稿指出，縣內今天新增確診1509例，年齡分布1歲以下至95歲，單日確診人數仍在高原期。衛生局統計，至6月18日止，縣內符合第4劑疫苗施打資格之65歲以上長者約有2萬2300餘人，將結合縣內醫院，利用18日週六上午，在苗栗、頭份、竹南、公館、後龍、苑裡、通霄7鄉鎮市同步開設莫德納疫苗大型接種站，優先提供65歲以上及55歲以上原住民長者接種疫苗，各場最後1小時也開放一般民眾施打。衛生局表示，其餘11鄉鎮則由轄區衛生所依村里規劃施打日程，長者依公告時段前往衛生所接種，相關訊息可上縣府衛生局網站查詢。衛生局長張蕊仙提醒，依據衛福部疾管署規定，建議染疫康復者於發病日或確診日（無症狀感染者）起，至少間隔3個月後，再施打COVID-19疫苗。


In [69]:
from operator import itemgetter
import pandas as pd
import numpy as np

In [70]:
df = pd.read_csv('vaccine_preprocessed_3.csv',sep='|')

In [71]:
news_sim_martrix = np.load('news_sim_martrix_3.npy')

In [72]:
item_id2idx={}
idx2item_id={}
for id, i in df.item_id.items():
    item_id2idx[i] = id
    idx2item_id[id] = i

In [73]:
def get_topk_news(item_id, news_sim_martrix, topk=3):
    sim_dict = {}
    idx = item_id2idx[item_id]
    for i, value in enumerate(news_sim_martrix[idx]):
        sim_dict[i]=value
    topk = sorted(sim_dict.items(), key= itemgetter(1), reverse=True)[1:topk+1]
    return topk

In [74]:
item_id = 4
#item_id = 'acn_20220313_20'
news_sim = get_topk_news(item_id, news_sim_martrix, topk=3)

In [75]:
for idx, value in news_sim:
    print(value, df.content.iloc[idx])

0.9842006 全球對抗新冠肺炎(COVID-19)疫情的日子已超過一年半，疫情下的艱困日常還有防疫疲勞，都讓人迫切關注疫情止息的線索。其中「群體免疫」是不少人的盼望，也是大多數國家努力的目標。但AZ(AstraZeneca)疫苗研發者竟然在日前受訪時大潑冷水，直言Delta病毒株的出現讓全球「不可能」實現群體免疫(herd immunity)，真是比悲傷更悲傷的事。根據世界衛生組織(WHO)定義，群體免疫是一種對傳染病的間接保護。當人群透過接種疫苗或者因為曾罹患該疾病而有免疫力，就會形成。針對當前全球正在對抗的新冠肺炎(COVID-19)疫情，世衛也支持透過接種疫苗來實現群體免疫的願景，而非放任疾病在部分人群中蔓延，造成不必要的染病或死亡。《自然》(Nature)期刊一篇研究指出，大多數傳染病的群體免疫門檻落在60%~70%之間。若你曾關注過台灣或其他國家宣告的群體免疫門檻，或許都差不多。但是牛津大學疫苗研究小組負責人，同時也是AZ疫苗研發者之一的Sir Andrew Pollard日前受訪時指出，Delta變種病毒的出現，已使得人類不可能達到COVID-19群體免疫。為什麼新冠肺炎群體免疫的終極目標無法實現？Pollard博士指出，是因為已證實Delta病毒株能感染完整接種疫苗者。換言之，完整接種疫苗僅能減緩疾病的傳播效率，無法完全阻隔病毒。Delta病毒使得COVID-19無法像麻疹一樣，只要有95%人口接種疫苗，就可防止病毒傳播。Delta病毒會讓已接種疫苗者也成為目標，也就是讓未接種疫苗者總有一天會受到感染，無法實現群體免疫的願景；除此之外，Pollard博士指出，目前人類缺乏可完全阻隔COVID-19疫情的技術。雖然完整接種後仍有突破性感染的風險，但並不代表疫苗無效。因為完整接種疫苗在感染Delta病毒後的症狀明顯減輕，大多數都是輕症，僅有極為少數的人住院或是死亡。在美國，絕大多數染疫住院者都是未接種疫苗的人，而完整接種的人住院比例僅有0.1%~5%，死亡率僅0.2%~0.6%。正是因為新冠病毒突變速度非常快，Pollard博士提醒下一個變種病毒的傳染力可能比Delta更高。因此思考與COVID-19共存的方式，還有加緊研發COVID-19療法更刻不容緩。因為接種疫苗對於部分免疫力低下的人來說效果不高，產生的保護力較低，因此數年內可能仍有不少人染疫後